config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams, except: [:show] do 
    resources :quiz_sessions, only: [:index, :new, :create, :destroy]
  end

  resource :auth, only: [:create] 

  root to: "teams#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz_session.rb
class QuizSession < ApplicationRecord
  belongs_to :team

  validates_presence_of :total_quiz_number, :correct_quiz_number
  validate :max_correct_quiz_number
  validates_numericality_of :total_quiz_number, :correct_quiz_number

  def max_correct_quiz_number
    return unless total_quiz_number && correct_quiz_number

    errors.add(:base, 'Number does not add up!') if correct_quiz_number > total_quiz_number
  end
end

app/models/team.rb
class Team < ApplicationRecord
  include BCrypt

  has_many :quiz_sessions, dependent: :delete_all
  has_one :auth_token

  validates_presence_of :name, :description
  validates_uniqueness_of :name
  validate :valid_password

  attr_accessor :password
  attr_accessor :pass_number

  def password
    Password.new(pass)
  end

  def password=(new_password)
    self.pass_number = new_password
    self.pass = Password.create(new_password)
  end

  private

  def valid_password
    range = %w( 1 2 3 4 5 6 7 8 9 0 )

    errors.add(:base, 'You need enter a password') unless pass_number

    if pass_number
      errors.add(:base, 'Passwod is like bank pass, 4 numbers') unless pass_number.size == 4
      pass_number.each_char do |number|
        errors.add(:base, 'Passwod is like bank pass, you should only enter numbers!') unless range.include? number
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  include Rails.application.routes.url_helpers

  def create
    @team = Team.find(params[:team_id])

    if @team.password == params[:pass].join
      @url = team_quiz_sessions_path(@team)
      session[:team] = @team 
      render :create, status: 200
    else
      @url = root_path
      render :create, status: 503
    end
  end

end

app/controllers/quiz_sessions_controller.rb
class QuizSessionsController < ApplicationController
  before_action :require_team_session

  def index
    @team = Team.find(params[:team_id])
    @sessions = QuizSession.where(team: params[:team_id]).all

    if @sessions.any?
      total = @sessions.map{|e| e.correct_quiz_number.to_f/e.total_quiz_number.to_f}
        .reduce(:+)
      overall_accuracy = (total/@sessions.size).to_f.round(2)
      @pie_series = [ {"values":[overall_accuracy * 100], "text":"Correct #{overall_accuracy}"}, {"values":[( 1 - overall_accuracy ) * 100], "text": "Incorrect #{(1 - overall_accuracy).round(2)}"} ]
      @bar_series = @sessions.map{|e| {value: ( e.correct_quiz_number.to_f/e.total_quiz_number.to_f ).round(2), happened_at: e.created_at.strftime('%F')}}
                             .map{|h| { values: [ h[:value] * 100 ], text: h[:happened_at] }}
    else
    end

  end

  def new
    @team = Team.find(params[:team_id])
    @session = @team.quiz_sessions.build(total_quiz_number: 15)
  end

  def create
    @team = Team.find(params[:team_id])
    @session = @team.quiz_sessions.build(quiz_session_params)

    if @session.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def destroy
    @team = Team.find(params[:team_id])
    @session = @team.quiz_sessions.find(params[:id])
    @session.destroy!

    redirect_to action: :index
  end

  private

  def quiz_session_params
    params.require(:quiz_session).permit!
  end

  def require_team_session
    team = session[:team]
    @team = Team.find(params[:team_id])
    if session[:team] && session[:team]['pass'] == @team.pass 
    else
      flash[:error] = "Can not let you do that !"
      redirect_to root_path and return
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def create
    @team = Team.new(name: team_params[:name], description: team_params[:description], password: team_params[:pass_number])

    if @team.save
      redirect_to teams_path
    else
      render :new
    end
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(name: team_params[:name], description: team_params[:description], password: team_params[:pass_number])
      flash[:notice] = 'You team detail has been updated'
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy!

    redirect_to action: :index
  end

  private

  def team_params
    params.require(:team).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NZX Quzi Count</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav">
      <div class="nav-center nav-menu">
        <a class="nav-item" href="<%= teams_path %>"> Home </a>
      </div>
    </nav>

    <div class="columns">
      <div class="column">
        <% if flash[:notice] %>
          <div class="notification"><%= flash[:notice] %></div>
        <% end %>
        <%if flash[:error]  %>
          <div class="notification is-danger"><%= flash[:error] %></div>
        <% end %>
      </div>
    </div>

    <div class="container is-fluid">
      <%= yield %>
    </div>
  </body>

</html>

app/views/quiz_sessions/index.html.erb
<div class="columns">
  <div class="column">
    <div class="field is-grouped pull-right">
      <%= link_to "Add new record", new_team_quiz_session_path(@team), class: 'button is-info is-outlined'%>
      <%= link_to "Edit team details", edit_team_path(@team), class: 'button is-info is-outlined'  %>
    </div>
  </div>
</div>

<% if @sessions.any? %>
<div class="columns is-mobile">
  <div class="column">
    <h3 class="title"> Overall accuracy </h3>
    <%= react_component("PieChart", {series: @pie_series}) %>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column">
    <%= react_component("BarChart", {series: @bar_series}) %>
  </div>
</div>

<div class="columns">
  <div class="column">
    <h3 class="title"> History </h3>
    <table class="table">
      <tr> 
        <td> When </td> 
        <td> Score </td> 
        <td> Accuracy </td> 
        <td></td> 
      </tr> 
      <% @sessions.each do |s| %>
      <tr>
        <td> <%= s.created_at.strftime('%F') %></td>
        <td> <%= s.correct_quiz_number %> / <%= s.total_quiz_number %></td>
        <td> <%= number_to_percentage((s.correct_quiz_number.to_f/s.total_quiz_number.to_f) * 100 )%> </td>
        <td></td>
        <td> <%= link_to "Delete", team_quiz_session_path(@team, s), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% else %>
<div class="columns">
  <div class="column">
    <p class="box"> Start to add record</p>
  </div>
</div>
<% end %>

app/views/quiz_sessions/new.html.erb
<div class="columns">
  <div class="column is-offset-10">
    <%= link_to "Go back to records history", team_quiz_sessions_path(@team), class: 'button'%>
  </div>
</div>

<div class="columns">
  <div class="column">
    <%= form_for @session, url: team_quiz_sessions_path(@team) do |f| %>
      <% if @session.errors.any? %>
        <div class="column notification is-danger">
          <%= @session.errors.full_messages.to_sentence %>
        </div>
      <% end %>

      <div class="column">
          <label class="label"> Total:</label> <%= f.text_field :total_quiz_number, class: 'input' %>
      </div>
      <div class="column">
          <label class="label"> Corrent:</label> <%= f.text_field :correct_quiz_number, class: 'input' %>
      </div>

      <div class="column">
        <%= f.submit "Save !", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>